channels:
- conda-forge
dependencies:
- python =3.12
- conda_subprocess =0.0.10
- executorlib =1.7.4
- pyiron_base =0.15.12
- pyiron_workflow =0.15.4
- python-workflow-definition =0.1.2
- pygraphviz =1.14
- pyironflow =0.0.21
